repos:
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: /data/dust/user/abaur/tau-lifetime/tau_pyenv_el9_v2/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
